services:
  uvend-app:
    build: .
    ports:
      - ${PORT:-3002}:3002
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3002}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
networks: {}
